/*
!!This script will delete your InterNatter database.
command: node task/seed.js
Generate data to database for test.
Just for test, all data in this file are hardcoded,
author: Haodong Wu
03/14 2021
*/
const mongoose = require('mongoose');
const User = require('../models/user');
const Chatroom = require('../models/chatroom');
const Message = require('../models/message');
const userFriends =  require('../models/friend')


const main = async () => {
    mongoose.connect('mongodb://localhost:27017/InterNatter', {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
    useFindAndModify: false
})

    const db = mongoose.connection;
    db.once("open", () => {
        console.log("Database connected");
    });

    db.dropDatabase();
    const data = [
        {
          "sender": "test",
          "originalMsg": "I am the best tester",
          "send_time": 1614905034820,
          "senderLang": "English",
          "image": "/images/avatars/default_avatar.png"
        },
        {
          "sender": "Jerry",
          "originalMsg": "Hello.",
          "send_time": 1614907034604,
          "senderLang": "English",
          "image": "https://tinyfac.es/data/avatars/A7299C8E-CEFC-47D9-939A-3C8CA0EA4D13-500w.jpeg"
        },
        {
          "sender": "zhao",
          "originalMsg": "Nice to meet you.",
          "send_time": 1614907035620,
          "senderLang": "English",
          "image": "https://tinyfac.es/data/avatars/B3CF5288-34B0-4A5E-9877-5965522529D6-500w.jpeg"
        },
        {
          "sender": "John",
          "originalMsg": "Hello.",
          "send_time": 1614907044604,
          "senderLang": "English",
          "image": "https://tinyfac.es/data/avatars/282A12CA-E0D7-4011-8BDD-1FAFAAB035F7-500w.jpeg"
        },
        {
          "sender": "Mike",
          "originalMsg": "Nice to meet you.",
          "send_time": 1614907134620,
          "senderLang": "English",
          "image": "https://tinyfac.es/data/avatars/BA0CB1F2-8C79-4376-B13B-DD5FB8772537-500w.jpeg"
        },
        {
          "sender": "Nicole",
          "originalMsg": "Bonjour je suis francais",
          "send_time": 1614907234604,
          "senderLang": "French",
          "image": "https://tinyfac.es/data/avatars/03F55412-DE8A-4F83-AAA6-D67EE5CE48DA-500w.jpeg"
        },
        {
          "sender": "whd",
          "originalMsg": "很高兴见到你",
          "send_time": 1614905034620,
          "senderLang": "Chinese (Simplified)",
          "image": "https://tinyfac.es/data/avatars/1C4EEDC2-FE9C-40B3-A2C9-A038873EE692-500w.jpeg"
        }
      ]
    let testUser = null; // this variable is used to add one creator to the chatroom.
    const chatroom = new Chatroom({title: "Let's talk", image:"https://cdn4.iconfinder.com/data/icons/communication-215/64/communications-talk-chat-conversation-consulting-512.png", description: "The chat room was generated by task/seed.js"});
    console.log('Done seeding database');
    for(var i = 0; i < data.length; i++) {
        let msg = data[i]
        let user = new User({ email: msg.sender + "@gmail.com", username: msg.sender, language: msg.senderLang, image: msg.image});
        if(!testUser){
          chatroom.creator = user.id;
          await chatroom.save();
          testUser = user;
        }else{
          let arr = [{userId: testUser.id, username:testUser.username, friendId: user.id, friendname:user.username}, {userId: user.id, username:user.username, friendId: testUser.id, friendname:testUser.username}]
            // new friend connection
            await userFriends.insertMany(arr,function (err, friend) {
              if (err) return console.error(err);
            }); 
            // new friend hello
            const hellos = {
              "English": "Hello",
              "French": "Bonjour je suis francais",
              "Chinese (Simplified)":"很高兴见到你"

            }
            await Message.createNew({
              sender: testUser.id,
              senderName: testUser.username,
              receiver: user.id,
              content: `${hellos[testUser.language]} ${user.username}`,
              originalLanguage: testUser.language,
              sendTime: new Date(msg.send_time)
            }
            )

            await Message.createNew({
              sender: user.id,
              senderName: user.username,
              receiver: testUser.id,
              content: `${hellos[user.language]} ${testUser.username}`,
              originalLanguage: user.language,
              sendTime: new Date(msg.send_time)
            }
            )
            
          
        }
        let registeredUser = await User.register(user, msg.sender);
          await Message.createNew({
            sender: user.id,
            senderName: msg.sender,
            receiver: chatroom.id,
            content: msg.originalMsg,
            originalLanguage: msg.senderLang,
            sendTime: new Date(msg.send_time)
          })
    };
    console.log('Done seeding database');
    process.exit();

}
main().catch(console.log);

module.exports = main;