/*
!!This script will delete your InterNatter database.
command: node task/seed.js
Generate data to database for test.
Just for test, all data in this file are hardcoded,
author: Haodong Wu
03/14 2021
*/
const mongoose = require('mongoose');
const User = require('../models/user');
const Chatroom = require('../models/chatroom');
const Message = require('../models/message');


const main = async () => {
    mongoose.connect('mongodb://localhost:27017/InterNatter', {
    useNewUrlParser: true,
    useCreateIndex: true,
    useUnifiedTopology: true,
    useFindAndModify: false
})

    const db = mongoose.connection;
    db.once("open", () => {
        console.log("Database connected");
    });

    db.dropDatabase();
    const data = [
        {
          "sender": "Jerry",
          "originalMsg": "Hello.",
          "send_time": 1614907034604,
          "senderLang": "English"
        },
        {
          "sender": "zhao",
          "originalMsg": "Nice to meet you.",
          "send_time": 1614907035620,
          "senderLang": "English"
        },
        {
          "sender": "John",
          "originalMsg": "Hello.",
          "send_time": 1614907044604,
          "senderLang": "English"
        },
        {
          "sender": "Mike",
          "originalMsg": "Nice to meet you.",
          "send_time": 1614907134620,
          "senderLang": "English"
        },
        {
          "sender": "Nicole",
          "originalMsg": "Hello.",
          "send_time": 1614907234604,
          "senderLang": "English"
        },
        {
          "sender": "whd",
          "originalMsg": "Nice to meet you.",
          "send_time": 1614905034620,
          "senderLang": "English"
        }
      ]
    const chatroom = new Chatroom({title: "Let's talk", image:"https://cdn4.iconfinder.com/data/icons/communication-215/64/communications-talk-chat-conversation-consulting-512.png", description: "The chat room was generated by task/seed.js"});
    await chatroom.save();
    for(var i = 0; i < data.length; i++) {
        let msg = data[i]
        let user = new User({ email: msg.sender + "@gmail.com", username: msg.sender, language: msg.senderLang });
        let registeredUser = await User.register(user, msg.sender);
          await Message.createNew({
            sender: user.id,
            senderName: msg.sender,
            receiver: chatroom.id,
            content: msg.originalMsg,
            originalLanguage: msg.senderLang,
            sendTime: new Date(msg.send_time)
          })
    };
    console.log('Done seeding database');

}
main().catch(console.log);

module.exports = main;